add attributes for Fill, Stroke, Width & Height
gitFoxCode/nuxt-icons pull request #3
Opened 2022-06-15 01:35 UTC by MrTechieCode

2022-10-21 16:01 UTC, AliQ80 requested changes
line 81 of README.md needs correction

2022-11-19 00:03 UTC, tpkee commented on src/runtime/components/nuxt-icon.vue
> +  </div>
Why use a flex box for an icon importer? More so, I think I think it's nice to have a width and height props while you could remove the stroke props and add the `v-bind="$attrs"` to the line 3-8 div (removing the line 2 div) so you can pass class directly to the icon too 
If I'm not mistaken right now you need to wrap `<nuxt-icon />` inside another element to pass some classes which is quite annoying

2022-12-03 16:58 UTC, Snitovets commented
I hope it will be merged soon

2023-02-21 19:50 UTC, eduayme commented
+1 I hope it will be merged

2023-03-23 14:21 UTC, the-missing-pink commented on src/runtime/components/nuxt-icon.vue
> +  <div class="nuxt-icon-container">
Don't use a container, if people want to use a icon, they expect to find a single element with the icon. The way it is set up now, you get a icon in a div in a div. If users would like to center their icon, they will do so themselves.

2023-08-29 08:49 UTC, closed without merging